version = 1

[[annotations]]
path = [
    ".clang-format",
    ".github/copilot-instructions.md",
    ".github/prompts/commands-api.md",
    ".gitignore",
    ".gitmodules",
    ".vscode/c_cpp_properties.json",
    ".vscode/settings.json",
    "README.md"
]
SPDX-FileCopyrightText = "Michael Fisher @mfisher31"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [
    "bindings/**/*.yaml"
]
SPDX-FileCopyrightText = "Michael Fisher @mfisher31"
SPDX-License-Identifier = "MIT"
