version = 1

[[annotations]]
path = [
    "**/*.md",
    "**/*.html",
    "README.md"
]
SPDX-FileCopyrightText = "Michael Fisher @mfisher31"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [
    "**/*.yaml",
    "**/*.yml",
    "**/*.json.in",
    "**/*.pom.in",
    ".gitignore",
    ".gitmodules",
    ".clang-format",
    ".vscode/c_cpp_properties.json",
    ".vscode/settings.json"
]
SPDX-FileCopyrightText = "Michael Fisher @mfisher31"
SPDX-License-Identifier = "MIT"
